schedule clear minecraft:tick/dot_tick_0
schedule clear minecraft:tick/dot_tick_1
schedule clear minecraft:tick/dot_tick_2
schedule clear minecraft:tick/dot_tick_3
schedule clear minecraft:tick/dot_tick_4
schedule clear minecraft:tick/dot_tick_5
schedule clear minecraft:tick/dot_tick_6
schedule clear minecraft:tick/dot_tick_7
schedule clear minecraft:tick/dot_tick_8
schedule clear minecraft:tick/dot_tick_9
schedule clear minecraft:tick/dot_tick_10
schedule clear minecraft:tick/dot_tick_11
schedule clear minecraft:tick/dot_tick_12
schedule clear minecraft:tick/dot_tick_13
schedule clear minecraft:tick/dot_tick_14
schedule clear minecraft:tick/dot_tick_15
schedule clear minecraft:tick/dot_tick_16
schedule clear minecraft:tick/dot_tick_17
schedule clear minecraft:tick/dot_tick_18
schedule clear minecraft:tick/dot_tick_19
schedule clear minecraft:tick/dot_tick_20
schedule clear minecraft:tick/dot_tick_21
schedule clear minecraft:tick/dot_tick_22
schedule clear minecraft:tick/dot_tick_23
schedule clear minecraft:tick/dot_tick_24
schedule clear minecraft:tick/dot_tick_25
schedule clear minecraft:tick/dot_tick_26
schedule clear minecraft:tick/dot_tick_27
schedule clear minecraft:tick/dot_tick_28
schedule clear minecraft:tick/dot_tick_29
schedule clear minecraft:tick/dot_tick_30
schedule clear minecraft:tick/dot_tick_31
schedule clear minecraft:tick/dot_tick_32
schedule clear minecraft:tick/dot_tick_33
schedule clear minecraft:tick/dot_tick_34
schedule clear minecraft:tick/dot_tick_35
schedule clear minecraft:tick/dot_tick_36
schedule clear minecraft:tick/dot_tick_37
schedule clear minecraft:tick/dot_tick_38
schedule clear minecraft:tick/dot_tick_39